import io
import logging
import base64
import requests
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel
from rembg import remove
from PIL import Image
from deep_translator import GoogleTranslator

# ---------------- Logging ----------------
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------- App ----------------
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------- Config ----------------
SD_API_URL = "http://127.0.0.1:7860/sdapi/v1/txt2img"

# ---------------- Models ----------------
class GenerateRequest(BaseModel):
    prompt: str
    category: str

class LocalizeRequest(BaseModel):
    text: str
    languages: list[str]

# ---------------- Style Presets ----------------
STYLE_PRESETS = {
    "Illustration": ", flat vector art, simple geometric shapes, clean lines, white background, adobe illustrator style",
    "Icon": ", app icon style, minimal, centered, thick lines, flat color, white background",
    "Background Element": ", decorative abstract shape, memphis design pattern, minimal, white background",
    "UI Graphic": ", ui sticker, modern web design element, flat, vibrant colors, white background",
    "Product Element": ", realistic isolated object, studio lighting, high detail, white background, 8k",
    "Decorative Shape": ", simple abstract blob, organic shape, solid color, flat, white background"
}

# ---------------- Routes ----------------
@app.get("/")
def root():
    return {"status": "Backend running (Gen + Loc)"}

# --- Feature 1: Localization Endpoint ---
@app.post("/localize")
async def localize_text(request: LocalizeRequest):
    logger.info(f"Translating '{request.text}' to {request.languages}")
    
    results = {}
    
    # Map UI language names to Google Translate codes
    lang_map = {
        "Hindi": "hi",
        "Marathi": "mr",
        "Spanish": "es",
        "French": "fr",
        "German": "de"
    }
    
    try:
        for lang_name in request.languages:
            target_code = lang_map.get(lang_name, "en")
            
            # Perform Translation
            translated = GoogleTranslator(source='auto', target=target_code).translate(request.text)
            results[lang_name] = translated
            
        logger.info(f"Translation results: {results}")
        return results
        
    except Exception as e:
        logger.error(f"Translation error: {e}")
        # Return fallback (original text) so UI doesn't break
        fallback = {lang: request.text for lang in request.languages}
        return fallback

# --- Feature 2: Asset Generation Endpoint ---
@app.post("/generate")
async def generate_asset(request: GenerateRequest):
    logger.info(f"Received request: {request.prompt} [{request.category}]")

    try:
        image_data = None

        try:
            logger.info("Connecting to Stable Diffusion...")

            style_suffix = STYLE_PRESETS.get(request.category, STYLE_PRESETS["Illustration"])
            enhanced_prompt = request.prompt + style_suffix

            payload = {
                "prompt": enhanced_prompt,
                "negative_prompt": "photorealistic, noisy, blurry, watermark, text, signature, shading, gradients, cropped, cut off",
                "steps": 25,
                "width": 512,
                "height": 512,
                "cfg_scale": 7
            }

            response = requests.post(SD_API_URL, json=payload, timeout=60)

            if response.status_code == 200:
                r = response.json()
                image_data = base64.b64decode(r["images"][0])
                logger.info("Image generated by Stable Diffusion")
            else:
                logger.warning(f"SD returned {response.status_code}")
                raise Exception("SD Error")

        except Exception as e:
            logger.warning(f"Stable Diffusion failed: {e}")
            # Fallback Image
            dummy_url = "https://cdn-icons-png.flaticon.com/512/4712/4712109.png"
            image_data = requests.get(dummy_url).content

        logger.info("Removing background...")
        input_image = Image.open(io.BytesIO(image_data))
        output_image = remove(input_image)

        logger.info("Sending PNG...")
        img_byte_arr = io.BytesIO()
        output_image.save(img_byte_arr, format="PNG")
        img_byte_arr.seek(0)

        return Response(content=img_byte_arr.getvalue(), media_type="image/png")

    except Exception as e:
        logger.error(f"Processing error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# ---------------- Run ----------------
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)